### PR TITLE
If this don't fix it ....

### PR DESCRIPTION
**Pull request by traugdor**
then idk what will

### CODE REVIEW

**Comment by shadowcodex** [comment]
What’s the issue?

**Comment by shadowcodex** [comment]
I’ve thought about rewriting this in vue

**Comment by traugdor** [comment]
Killboard broke... Massively

On Jan 13, 2018 5:00 PM, "Shannon Duncan" <notifications@github.com> wrote:

I’ve thought about rewriting this in vue

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/shadowcodex/cryrs-site/pull/3#issuecomment-357474267>,
or mute the thread

**Comment by shadowcodex** [comment]
I’ll take a look this week.

**Comment by traugdor** [comment]
Its fixed now

**Comment by shadowcodex** [comment]
Oh cool

**Pull request merged**
